proposals/20210404-sklearn_example.md

Trying to get project automation to trigger.

Sklearn Example

---

.github/ci/.pre-commit-config.yaml
pyproject.toml

Fixes issue with CI due to change in project folders.

Update ci ignore

---

README.md

Small PR to add GitHub CI status on README

Add GitHub CI badge to README

---

examples/sklearn_penguins/penguin_pipeline_sklearn_gcp.py
examples/sklearn_penguins/penguin_pipeline_sklearn_gcp_test.py
examples/sklearn_penguins/penguin_pipeline_sklearn_local.py
examples/sklearn_penguins/penguin_pipeline_sklearn_local_e2e_test.py
examples/sklearn_penguins/penguin_utils_sklearn.py
examples/sklearn_penguins/sklearn_predict_extractor.py
examples/sklearn_penguins/sklearn_predict_extractor_test.py

fix isort, yapf, and linter issues for sklearn example

---

.github/ci/.pre-commit-config.yaml
.github/ci/.pylintrc
.github/ci/.style.yapf
.github/workflows/ci.yml
.github/workflows/lint.yml
examples/sklearn_penguins/penguin_pipeline_sklearn_gcp.py
examples/sklearn_penguins/penguin_pipeline_sklearn_gcp_test.py
examples/sklearn_penguins/sklearn_predict_extractor.py
examples/sklearn_penguins/sklearn_predict_extractor_test.py
pyproject.toml

Add back penguin sklearn to pre-commit checks

---

README.md

Add Slack to README

---

tfx_addons/mlmd_client/README.md

Testing automerge!

---

README.md

Add badges for both CI jobs

---

projects/feature-store-connector/feast_example_gen/protos/FeastConfig.proto
projects/feature-store-connector/feast_example_gen/protos/feast/core/CoreService.proto
projects/feature-store-connector/feast_example_gen/protos/feast/core/DataFormat.proto
projects/feature-store-connector/feast_example_gen/protos/feast/core/DataSource.proto
projects/feature-store-connector/feast_example_gen/protos/feast/core/Entity.proto
projects/feature-store-connector/feast_example_gen/protos/feast/core/Feature.proto
projects/feature-store-connector/feast_example_gen/protos/feast/core/FeatureService.proto
projects/feature-store-connector/feast_example_gen/protos/feast/core/FeatureTable.proto
projects/feature-store-connector/feast_example_gen/protos/feast/core/FeatureView.proto
projects/feature-store-connector/feast_example_gen/protos/feast/core/FeatureViewProjection.proto
projects/feature-store-connector/feast_example_gen/protos/feast/core/OnDemandFeatureView.proto
projects/feature-store-connector/feast_example_gen/protos/feast/core/Registry.proto
projects/feature-store-connector/feast_example_gen/protos/feast/core/Store.proto
projects/feature-store-connector/feast_example_gen/protos/feast/types/EntityKey.proto
projects/feature-store-connector/feast_example_gen/protos/feast/types/Field.proto
projects/feature-store-connector/feast_example_gen/protos/feast/types/Value.proto

Adding protobuf definitions for initializing Feast to connect to data provider (local or remote in gcp/aws).

Adding basic feast connection config

---

proposals/20210525-feast_example_gen.md

Proposal for the feature store connector discussed in #4.

Proposal feast connector

---

CODEOWNERS
proposals/20210525-feast_example_gen.md

Add developers on feast examplegen into CODEOWNERS

Add owners to feast examplegen

---

.github/workflows/ci.yml
.github/workflows/ci_examples.yml

Update CI to improve caching and add test for tfx 1.3

Update ci to improve cache and test tfx 1.3

---

README.md

Dropping off the effort, thanks and bye folks!

Update README.md to reflect membership changes

---

proposals/20211124-model_card_component.md

Updates ModelCardComponent proposal. Specifically, replaces the "TfxModelCardToolkit" class, which offers a new API for TFX artifacts, with a "Source" class that handles model card inputs.

ModelCardComponent proposal - update source API

---

CODEOWNERS

Follow up for #100 also adding myself and @cent5 to projects to make sure we have current owners.

Adding myself to projects and removing Sam from owners

---

proposals/20220117-exit-handler-slack.md

Proposal related to #101 
The implementation is done and the Digits' ML team would like to open-source the implementation.

Slack exit handler proposal

---

CODEOWNERS

I don't have enough expertise to review these PRs and the way this file is configured I get added to review all PRs to the repo.
Instead, if there's a PR that I should review, please tag me. This way, I'll know to only react to the ones that are relevant.

Removing myself from `CODEOWNERS`

---

CONTRIBUTING.md

Fixes #<issue_number_goes_here>
> It's a good idea to open an issue first for discussion.
- [NA] Tests pass
- [NA] Appropriate changes to README are included in PR

Added section about code ownership rules

---

.github/workflows/ci.yml
.github/workflows/ci_examples.yml
setup.py
tfx_addons/xgboost_evaluator/xgboost_predict_extractor.py

Upgrade to tfx 1.7 in CI

---

.github/license-templates/LICENSE.txt
.github/workflows/ci.yml
.github/workflows/publish-to-test-pypi.yml
README.md
RELEASE.md
setup.py
tfx_addons/__init__.py
tfx_addons/version.py

@casassg initial release notes. Just a proposal based on the TF Addons setup. 
Would love to connect regarding the `nighly` build setup.

Release proposal

---

tfx_addons/version.py

Initial release candidate for TFX Addons.
Merge checklist:

Prepare 0.1.0rc0

---

.github/workflows/release.yml
RELEASE.md

* Update release workflow
* update release workflow
* add note to update main w next minor number
Fixes #<issue_number_goes_here>
> It's a good idea to open an issue first for discussion.

Update release workflow (#121)

---

setup.py

Seems the existing setup.py didn't include some packages due to missing init files. This should address it.

Add root packages to 0.1.0 candidate

---

tfx_addons/version.py

Small change to update version under main

Bump version to 0.3.0dev0 as 0.2.0 is in rc0

---

README.md

Missed this in the previous change

Fix bad link in xgboost_evaluator

---

CODEOWNERS

Small change to add version file owners in CODEOWNERS

Add version file owners

---

.github/workflows/ci.yml
.github/workflows/ci_examples.yml
tfx_addons/message_exit_handler/component.py
tfx_addons/message_exit_handler/component_test.py
tfx_addons/version.py

Increase supported version from TFX <1.8 to <1.9 

---

tfx_addons/version.py

support tfx 1.9

---

.github/workflows/ci.yml
.github/workflows/filter_projects.py

Small issue I did in filter projects new logic

small fix for filter projects

---

README.md

Add missing component links to README.

Update README to add missing component

---

tfx_addons/feature_selection/RELEASE.md

Added release notes for feature selection component

---

.github/workflows/ci_examples.yml
.github/workflows/filter_examples.py
.github/workflows/filter_projects.py
CONTRIBUTING.md

Reproduce same things as main CI to automatically pick up what examples to  run against CI automatically.

Improve examples CI to automatically pick up projects

---

README.md
tfx_addons/utils/test_utils.py
tfx_addons/version.py

Add support for TFX 1.10. Also introduces a small fix to handle pre-releases in test_utils

Support TFX 1.10

---

CODEOWNERS

As proposed in https://github.com/tensorflow/tfx-addons/blob/main/proposals/20220823-huggingface_model_pusher.md

Add HF pusher owners

---

tfx_addons/version.py

Updating master to 0.5 after 0.4.0 release

---

RELEASE.md

Fix broken version.py links and change `master` branch links to `main`.

Fix broken links in RELEASE.md

---

.github/workflows/minor_release.yml
.github/workflows/prepare_minor_release.py
.github/workflows/update_main.py
RELEASE.md

Trying to automate experimental minor_release workflow.
This workflow creates a new branch, and drafts a new release.
Test run on my side: https://github.com/casassg/tfx-addons/actions/runs/4067327571
PR updating main: https://github.com/casassg/tfx-addons/pull/8
Pre-release: https://github.com/casassg/tfx-addons/releases/tag/c0.5.0rc0

Experimental minor_release workflow

---

README.md

Added HuggingFacePusher into Projects in README. Also ordered them alphabetically to make it easier to compare with https://github.com/tensorflow/tfx-addons/tree/main/tfx_addons.

Update projects on README

---

proposals/20230209-copy_example_gen.md

Project Proposal for #66 CopyExampleGen

Create 20230209-copy_example_gen.md Project Proposal: Ready for review

---

proposals/20230328-airflow_orchestration.md

Wrote a Apache-Airflow for Pipeline Orchestration proposal (cc: @rcrowe-google)

Add Apache-Airflow for Pipeline Orchestration proposal

---

tfx_addons/model_card_generator/executor.py

Fixes #261
I updated the MCT generator to create a temp dir for all cases since I don't think that's a big operation.

Support remote storage in modelcardgenerator

---

tfx_addons/feast_examplegen/README.md

Small update for getting a better version of the README working

Update Feast component description
