.github/ci/.pre-commit-config.yaml, .github/workflows/ci.yml, .github/workflows/lint.yml
Update to run pre-commit on all examples and separate from pytest CI to be able to be general for all.
=> Moving pre-commit to a separate workflow

.github/workflows/automerge.yml
Due to how we currently have set up the repository, only few people can write. 
However, we can automate some of the merges to the repository by using https://github.com/marketplace/actions/auto-merge-bot (based mostly on https://github.com/OSS-Docs-Tools/code-owner-self-merge)
This action uses codeowners file to determine who needs to review the PR and validates that enough users have approved it. 
Once enough approvals happen, the bot will automatically merge it into master. This allows us to develop on the repo without having to ask for @rcrowe-google to review and merge every time!
=> Propose using automerge in repo

.github/workflows/automerge.yml, CODEOWNERS, CONTRIBUTING.md
Adds some documentation for automerge and setup for auto-labeling PRs
In addition, also upgraded the bot to avoid assigning reviewers for now (to avoid too much noise for contributors) and set it up to squash when merging (instead of merge) to have a cleaner main branch.
=> Add documentation for automerge and remove auto-assignation for PRs

proposals/20210817-firebase_ml_publisher_component.md
Proposal for project idea discussed in #59
=> Project proposal for Firebase ML Publisher custom component 

tfx_addons/xgboost_evaluator/xgboost_predict_extractor.py, tfx_addons/xgboost_evaluator/xgboost_predict_extractor_test.py
xgboost evaluator was using internal modules of TFMA dependency. This means it broke easily on upgrade. Instead we are using now forward compatible TFMA imports which should be more stable.
=> Update xgboost evaluator to use forward compatible tfma imports

CODEOWNERS
Added @vulkomilev in the CODEOWNER for CI next to @casassg
> It's a good idea to open an issue first for discussion.
=> added vulkomilev to the CODEOWNERS for CI

proposals/20220118-upload_predictions_to_bigquery.md
The proposal suggests a component to address #78.
=> Component to write BulkInferrer Results to BigQuery

.github/workflows/ci.yml
My hypothesis is now we should be able to just use the normal constraint as pip installs from scratch either way. So no cache.
=> Remove pyarrow note

.github/workflows/release.yml, RELEASE.md
The current release format won't work since only commits tagged in main will work. 
Alternatively, we just release whenever a release is created from the releases page. Which is provides a more reproducible default.
=> Update release workflow

tfx_addons/version.py
Release 0.1.0 based on 0.1.0rc3.
Once merged:
- Trigger a new GitHub Release using 0.1.0 as release name and tag.
=> Release 0.1.0

.github/workflows/ci.yml, .github/workflows/ci_examples.yml, README.md, examples/xgboost_penguins/penguin_pipeline_local.py, examples/xgboost_penguins/penguin_pipeline_local_e2e_test.py, examples/xgboost_penguins/utils.py, setup.py, tfx_addons/__init__.py, tfx_addons/mlmd_client/__init__.py, tfx_addons/sampling/__init__.py, tfx_addons/version.py, tfx_addons/xgboost_evaluator/__init__.py, tfx_addons/xgboost_evaluator/xgboost_predict_extractor.py, tfx_addons/xgboost_evaluator/xgboost_predict_extractor_test.py
This is quite large change, but mostly it just includes a refactor TFX Addons README. Due to that, I had to restructure some parts of CI. Also I'm adding an easier way to import modules by doing `import tfx_addons as tfxa` similar to how tf-addons and tfx style does it. This should also give us more control over how to expose modules in tfxaddons while still develop in the repo.
Finally in the process of testing this realized xgboost evaluator was broken so fixed it and added it to the xgboost_penguin test.
I can break this change into smaller pieces as well.
=> Improve TFX Addons README, creates tfx_addons.{module} root imports and fix xgboost penguin example

.github/workflows/cherry-pick.yml, .github/workflows/cherrypick.yml, RELEASE.md
Adds https://github.com/vendoo/gha-cherry-pick to cherry pick commit back to previous versions for easier development (I want to avoid having to manually cherry pick commits to back port them to a release branch)
ToDo:
- Document usage for bot
=> Cherry pick bot to backport changes

README.md
Commit 93fd0062d962470a7c76998a51a7697d208a7dde didn't completely fix the link.
=> Fix bad link in xgboost_evaluator

tfx_addons/version.py
Use https://github.com/feast-dev/feast/releases/tag/v0.21.3 to have tfx-addons resolve with feast.
=> Bump feast version support

.github/workflows/ci_examples.yml, .github/workflows/filter_examples.py, .github/workflows/filter_projects.py
Make sure to run all CI if its a push event.
This ensures we have healthy release branches and main.
=> CI: Run all if event name is push

tfx_addons/firebase_publisher/README.md
update firebase publisher proposal with more detailed descriptions
changes
- function based -> class based, since this can be implemented easier by inheriting Pusher
- input/outputs information
- custom_config to be provided
- not only `TFLite` but also `SavedModel` is directly supported
I have implemented FirebasePublisher component based on this. Once this is merged, I will immediately create another PR for the code implementation. Please take a look @rcrowe-google, @casassg, @sayakpaul
=> update firebase publisher proposal

proposals/20220823-huggingface_model_pusher.md
Wrote a HFModelPusher component proposal (cc: @sayakpaul as the co-developer)
=> HFModelPusher component proposal

proposals/20220823-huggingface_model_pusher.md
integrated HuggingFace Space pushing capability into the HFModelPusher component proposal(#174)
cc: @sayakpaul
=> (proposal update) Add HuggingFace Space pushing capability to the HFModelPusher

proposals/20220802-project_pytorch_example.md
Proposal to address #156 - PyTorch TFX Example
=> PyTorch TFX proposal

tfx_addons/huggingface_pusher/runner.py
I found a bug in the HFPusher component that tries to replace contents in a file with given text even if the file is a binary type. This causes an error, so I have added a simple filtering logic to identify only text based files.
=> fix: filter non-text files for text replacement

.github/ci/.pre-commit-config.yaml, tfx_addons/version.py
Current last version may not resolve feast dep due to feast>=0.23 upgrading their numpy version which does not resolve on py 3.7.
This is an attempt to fix it before we drop py 3.7.
Updated minimal version supported which grants a new release but it was needed as I couldn't find a way to make it work with the existing versions without having to pin the entirety of Google repos.
Also had to upgrade isort in pre-commit due to an issue in the dependency as seen in https://github.com/home-assistant/core/issues/86892
=> Pin down feast dependency

CODEOWNERS, tfx_addons/predictions_to_biquery/__init__.py, tfx_addons/predictions_to_biquery/component.py, tfx_addons/predictions_to_biquery/executor.py, tfx_addons/predictions_to_biquery/test_component.py, tfx_addons/predictions_to_biquery/utils.py
Add skip annotations to all files from BQ exporter. Run YAPF and isort on files to make sure they are correctly formatted (also didn't find an easy way to skip running it)
=> Add skip annotations to BQ export files

tfx_addons/predictions_to_bigquery/component.py, tfx_addons/predictions_to_bigquery/executor.py, tfx_addons/predictions_to_bigquery/test_component.py, tfx_addons/predictions_to_bigquery/utils.py
Fixes #215 .
Minimum changes to get pre-commit checks to pass without ignoring the files (i.e. pylint: skip-file).
- [ X ] Tests pass
=> Fix lint errors in predictions_to_bigquery files.

tfx_addons/predictions_to_bigquery/executor.py, tfx_addons/predictions_to_bigquery/executor_test.py
Updates process method to parse the element (PredictionLog) and extract the input tf.Example as dict and combine it with the prediction results.
Fixes #218 
> It's a good idea to open an issue first for discussion.
- [ X ] Tests pass
- [ X ] Appropriate changes to README are included in PR
=> predictions-to-bigquery: Update FilterPredictionToDictFn.

.github/workflows/ci.yml, .github/workflows/ci_examples.yml, .github/workflows/release.yml
Switch to use new GITHUB_OUTPUT file instead and skip matrix if array is empty
=> Update CI to skip matrix if no job needed

examples/model_card_generator/MLMD_Model_Card_Toolkit_Demo.ipynb
Updates links in Model Card Generator example notebook and fixes some markdown formatting errors.
=> Update links in Model Card Generator example notebook

tfx_addons/copy_example_gen/README.md, tfx_addons/copy_example_gen/component.py, tfx_addons/copy_example_gen/component_test.py, tfx_addons/version.py
- Adds tests for the CopyExampleGen component.
- Reorganizes CopyExampleGen component file to have multiple helper functions for easier testing.
- Modifies `tfx_addons/copy_example_gen/README.md` for capitalization nits.
Checks:
=> CopyExampleGen tests

.gitignore, tfx_addons/model_card_generator/component.py, tfx_addons/model_card_generator/component_test.py, tfx_addons/model_card_generator/executor.py, tfx_addons/model_card_generator/executor_test.py
Model Card Toolkit supports filtering features and metrics when annotating a model card. This change surfaces `features_include`, `features_exclude`, `metrics_include`, and `metrics_exclude` parameters to enable filtering features and metrics through the `ModelCardGenerator` component as well.
Fixes [issue reported in the tfxa Google Group](https://groups.google.com/a/tensorflow.org/g/sig-tfx-addons/c/xV_ltbl0K24/m/AKQe_HgOAQAJ).
=> Enable filtering features and metrics in the ModelCardGenerator

tfx_addons/model_card_generator/component.py
Fix the typo in the ModelCardGenerator component.
=> Fix typo in `tfx_addons/model_card_generator/component.py`
